PINS = {
    "SCRODSEL" : 28,
    "TESTEN" : 29,
    "INTERRUPT" : 7,
    "TMS" : 14,
    "TDO" : 15,
    "TDI" : 18,
    "BMBSRCLK" : 23,
    "BMARCLK" : 24,
    "BMASRCLK" : 25,
    "TCK" : 4,
    "BMBRCLK" : 27,
    "SRA" : 22,
    "SRB" : 17,
    "TEST1" : 9,
    "DISPRES" : 30,
    "DISPDC" : 31,
}
